baseURL = "https://YOUR_NAME.github.io/"
languageCode = "en-US"
title = "YOUR_TITLE"
theme = "hago"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
disqusShortname = "YOUR_DISQUS_SHORT_NAME"
googleAnalytics = "UA-XXXXXXXXX-X"
paginate = 4


[Params]
  description = "DESCRIPTION"
  subtitle = "YOUR_SUB_TITLE"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  comments = true

[Author]
  name = "YOUR_NAME"
  website = "https://YOUR_NAME.github.io"
